name: Benchmark

on: [ pull_request ]

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-18.04
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: "github.ref != 'refs/heads/master'"

  bench:
    name: Benchmark (Go ${{ matrix.go }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.14]
        os: [ "ubuntu-18.04"]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
      - name: Benchmark
        run: |
          go run ./tests/echo_server &
          sleep 3
          go run ./tests/echo_client
